services:
  hyvor-reader-frontend:
    container_name: hyvor-reader-frontend
    build:
      context: .
      target: frontend-dev
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/static:/app/frontend/static
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
      - ./frontend/package.json:/app/frontend/package.json
      - ./frontend/package-lock.json:/app/frontend/package-lock.json
      - ./frontend/tsconfig.json:/app/frontend/tsconfig.json
      - ./frontend/svelte.config.js:/app/frontend/svelte.config.js
      - ./shared:/app/shared
    labels:
      traefik.enable: true
      traefik.http.routers.hyvor-reader-frontend.rule: Host(`reader.hyvor.localhost`)
      traefik.http.routers.hyvor-reader-frontend.tls: true
      traefik.http.routers.hyvor-reader-frontend.middlewares: vite-retry@file
      traefik.http.routers.hyvor-reader-frontend.entrypoints: https
      traefik.http.services.hyvor-reader-frontend.loadbalancer.server.port: 80
    networks:
      - hyvor-network
    # profiles: [dev]
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app/frontend
        - action: sync
          path: ./shared
          target: /app/shared

  hyvor-reader-backend:
    container_name: hyvor-reader-backend
    build:
      context: .
      target: backend-dev
    volumes:
      - ./backend:/app/backend
      - ../internal:/app/backend/vendor/hyvor/internal:ro
      - ./shared:/app/shared
    labels:
      traefik.enable: true
      traefik.http.routers.hyvor-reader-backend.rule: Host(`reader.hyvor.localhost`) && PathPrefix(`/api`)
      traefik.http.routers.hyvor-reader-backend.entrypoints: https
      traefik.http.routers.hyvor-reader-backend.tls: true
      traefik.http.routers.hyvor-reader-backend.service: hyvor-reader-backend
      traefik.http.services.hyvor-reader-backend.loadbalancer.server.port: 80
    networks:
      - hyvor-network
    # profiles: [dev]
    healthcheck:
      test: ls
      disable: true
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
        - action: sync
          path: ./shared
          target: /app/shared

  # postgres:
  #   image: postgres:16
  #   container_name: hyvor-reader-postgres
  #   environment:
  #     POSTGRES_DB: hyvor_reader
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - hyvor-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  # traefik:
  #   image: traefik:v3.4
  #   container_name: hyvor-reader-traefik
  #   command:
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.http.address=:80"
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   profiles:
  #     - traefik
  #   networks:
  #     - hyvor-network

networks:
  hyvor-network:
    external: true

# volumes:
#   postgres_data:
