services:
  hyvor-reader-frontend:
    container_name: hyvor-reader-frontend
    build:
      context: .
      target: frontend-dev
    labels:
      traefik.enable: true
      traefik.http.routers.hyvor-reader-frontend.rule: Host(`reader.hyvor.localhost`)
      traefik.http.routers.hyvor-reader-frontend.tls: true
      traefik.http.routers.hyvor-reader-frontend.middlewares: vite-retry@file
      traefik.http.routers.hyvor-reader-frontend.entrypoints: https
      traefik.http.services.hyvor-reader-frontend.loadbalancer.server.port: 80
    networks:
      - hyvor-network
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app/frontend
          ignore:
            - frontend/node_modules/
            - frontend/.svelte-kit/
            - frontend/build/
        - action: sync
          path: ./shared
          target: /app/shared

  hyvor-reader-backend:
    container_name: hyvor-reader-backend
    build:
      context: .
      target: backend-dev
    volumes:
      - ./backend:/app/backend
      # - ../internal:/app/backend/vendor/hyvor/internal:ro
      - ./shared:/app/shared
    labels:
      traefik.enable: true
      traefik.http.routers.hyvor-reader-backend.rule: Host(`reader.hyvor.localhost`) && PathPrefix(`/api`)
      traefik.http.routers.hyvor-reader-backend.entrypoints: https
      traefik.http.routers.hyvor-reader-backend.tls: true
      traefik.http.routers.hyvor-reader-backend.service: hyvor-reader-backend
      traefik.http.services.hyvor-reader-backend.loadbalancer.server.port: 80
    networks:
      - hyvor-network
    # profiles: [dev]
    healthcheck:
      test: ls
      disable: true
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
        - action: sync
          path: ./shared
          target: /app/shared

networks:
  hyvor-network:
    external: true
