services:
  hyvor-reader-frontend:
    container_name: hyvor-reader-frontend
    build:
      context: .
      target: frontend-dev
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/static:/app/frontend/static
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
      - ./frontend/package.json:/app/frontend/package.json
      - ./frontend/package-lock.json:/app/frontend/package-lock.json
      - ./frontend/tsconfig.json:/app/frontend/tsconfig.json
      - ./frontend/svelte.config.js:/app/frontend/svelte.config.js
      - ./shared:/app/shared
    labels:
      traefik.enable: true
      traefik.http.routers.hyvor-reader-frontend.rule: Host(`localhost`)
      traefik.http.routers.hyvor-reader-frontend.entrypoints: http
      traefik.http.services.hyvor-reader-frontend.loadbalancer.server.port: 80
    networks:
      - hyvor-network
    # profiles: [dev]

  hyvor-reader-backend:
    container_name: hyvor-reader-backend
    build:
      context: .
      target: backend-dev
    volumes:
      - ./backend:/app/backend
      - ../internal:/app/backend/vendor/hyvor/internal:ro
      - ./shared:/app/shared
    labels:
      traefik.enable: true
      traefik.http.routers.hyvor-reader-backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.routers.hyvor-reader-backend.entrypoints: http
      traefik.http.routers.hyvor-reader-backend.service: hyvor-reader-backend
      traefik.http.services.hyvor-reader-backend.loadbalancer.server.port: 80
    networks:
      - hyvor-network
    depends_on:
      postgres:
        condition: service_healthy
    # profiles: [dev]
    healthcheck:
      test: ls
      disable: true

  postgres:
    image: postgres:16
    container_name: hyvor-reader-postgres
    environment:
      POSTGRES_DB: hyvor_reader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hyvor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  traefik:
    image: traefik:v3.4
    container_name: hyvor-reader-traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - hyvor-network

networks:
  hyvor-network:
    external: true

volumes:
  postgres_data:
