framework:
    messenger:
        # failure_transport: failed

        transports:
            # scheduler_default will be auto-created for schedule 'default'

        routing:
            # No explicit routing needed - scheduler messages will use the default transport

when@test:
    framework:
        messenger:
            transports:
                scheduler_default: 'sync://'
