services:
  hyvor-service-pgsql:
    container_name: hyvor-service-pgsql
    image: postgres:16.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hyvor_reader_testing
    networks:
      - ci

networks:
  ci:
    external: true
